### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by Valentin-Bio** [frubino/mgkit#4]
Hello, I'm trying to use `hmmer2gff` program. I first created my per domain hit table by using hmmsearch as the following:

`hmmsearch --domtblout dom_results.txt --cpu 10 hydrocarbon.hmm translated_orfs.faa > hmm_results.log`

after that, I run `hmmer2gff` but I have the following error message:

`hmmer2gff -d -o sample1.gff translated_orfs.faa dom_results.txt`

> INFO - mgkit.io.fasta: Read 6846732 fasta sequences
> INFO - mgkit.workflow.hmmer2gff: Parsing HMMER data from file dom_results.txt
> INFO - mgkit.workflow.hmmer2gff: Writing GFF data to file sample1.gff
> Traceback (most recent call last):
>   File "/Users/valentin-ignacio/opt/miniconda3/envs/mgkit/bin/hmmer2gff", line 11, in <module>
>     sys.exit(main())
>   File "/Users/valentin-ignacio/opt/miniconda3/envs/mgkit/lib/python2.7/site-packages/mgkit/workflow/hmmer2gff.py", line 212, in main
>     options
>   File "/Users/valentin-ignacio/opt/miniconda3/envs/mgkit/lib/python2.7/site-packages/mgkit/workflow/hmmer2gff.py", line 178, in parse_domain_table_contigs
>     noframe=options.no_frame,
>   File "/Users/valentin-ignacio/opt/miniconda3/envs/mgkit/lib/python2.7/site-packages/mgkit/io/gff.py", line 1439, in from_hmmer
>     contig, frame = line[0].rsplit('-', 1)
> ValueError: need more than 1 value to unpack

**Comment by dwill023** [comment]
I installed mgkit with the verison 0.4.2 using conda as shown here https://anaconda.org/bioconda/mgkit. 
I too ran the same commands as Valentin-Bio and I get similar errors:

```sh
hmmscan --domtblout /ex/results/globins45_domtbl.txt /ex/data/Pfam-A.hmm /ex/inst/extdata/globins45.fa
# hmmscan :: search sequence(s) against a profile database
# HMMER 3.4 (Aug 2023); http://hmmer.org/
# Copyright (C) 2023 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query sequence file:             /ex/inst/extdata/globins45.fa
# target HMM database:             /ex/data/Pfam-A.hmm
# per-dom hits tabular output:     /ex/results/globins45_domtbl.txt
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

hmmer2gff -db PFAM inst/extdata/globins45.fa results/globins45_domtbl.txt

INFO - mgkit.io.utils: Detecting Compressed File Handle
INFO - mgkit.io.fasta: Reading fasta file inst/extdata/globins45.fa
Traceback (most recent call last):
  File "/home/dwilliams/miniconda3/envs/mgkit/bin/hmmer2gff", line 11, in <module>
    sys.exit(main())
  File "/home/dwilliams/miniconda3/envs/mgkit/lib/python3.7/site-packages/mgkit/workflow/hmmer2gff.py", line 212, in main
    options
  File "/home/dwilliams/miniconda3/envs/mgkit/lib/python3.7/site-packages/mgkit/workflow/hmmer2gff.py", line 153, in parse_domain_table_contigs
    aa_seqs = get_aa_data(options.aa_file)
  File "/home/dwilliams/miniconda3/envs/mgkit/lib/python3.7/site-packages/mgkit/workflow/hmmer2gff.py", line 143, in get_aa_data
    for name, seq in fasta.load_fasta(f_handle)
  File "/home/dwilliams/miniconda3/envs/mgkit/lib/python3.7/site-packages/mgkit/workflow/hmmer2gff.py", line 142, in <genexpr>
    (name.split(' ')[0], seq)
  File "/home/dwilliams/miniconda3/envs/mgkit/lib/python3.7/site-packages/mgkit/io/fasta.py", line 41, in load_fasta
    line = line.decode('ascii')
AttributeError: 'str' object has no attribute 'decode'
```

Here's the first few lines of my globins45.fa file
```
>MYG_ESCGI 
VLSDAEWQLVLNIWAKVEADVAGHGQDILIRLFKGHPETLEKFDKFKHLK
TEAEMKASEDLKKHGNTVLTALGGILKKKGHHEAELKPLAQSHATKHKIP
IKYLEFISDAIIHVLHSRHPGDFGADAQAAMNKALELFRKDIAAKYKELG
FQG
>MYG_HORSE 
GLSDGEWQQVLNVWGKVEADIAGHGQEVLIRLFTGHPETLEKFDKFKHLK
TEAEMKASEDLKKHGTVVLTALGGILKKKGHHEAELKPLAQSHATKHKIP
```

This is everything in my conda environment 
```
# packages in environment at /home/dwilliams/miniconda3/envs/mgkit:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
blas                      1.0                         mkl  
blosc                     1.21.3               h6a678d5_0  
bottleneck                1.3.5            py37h7deecbd_0  
brotli                    1.0.9                h5eee18b_8  
brotli-bin                1.0.9                h5eee18b_8  
brotlipy                  0.7.0           py37h27cfd23_1003  
bzip2                     1.0.8                h5eee18b_6  
c-ares                    1.19.1               h5eee18b_0  
ca-certificates           2024.9.24            h06a4308_0  
certifi                   2022.12.7        py37h06a4308_0  
cffi                      1.15.1           py37h5eee18b_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4            py37h06a4308_0  
cryptography              39.0.1           py37h9ce1e76_0  
curl                      8.2.1                h37d81fd_0  
cycler                    0.11.0             pyhd3eb1b0_0  
cyrus-sasl                2.1.28               h9c0eb46_1  
dbus                      1.13.18              hb2f20db_0  
exceptiongroup            1.2.2                    pypi_0    pypi
expat                     2.6.3                h6a678d5_0  
fftw                      3.3.9                h5eee18b_2  
flit-core                 3.6.0              pyhd3eb1b0_0  
fontconfig                2.14.1               h4c34cd2_2  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               h4a9f257_0  
future                    0.18.3           py37h06a4308_0  
giflib                    5.2.2                h5eee18b_0  
glib                      2.78.4               h6a678d5_0  
glib-tools                2.78.4               h6a678d5_0  
gst-plugins-base          1.14.1               h6a678d5_1  
gstreamer                 1.14.1               h5eee18b_1  
hdf5                      1.10.6               h3ffc7dd_1  
htseq                     0.11.3           py37hb3f55d8_0    bioconda
icu                       58.2                 he6710b0_3  
idna                      3.4              py37h06a4308_0  
importlib-metadata        4.11.3           py37h06a4308_0  
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
jpeg                      9e                   h5eee18b_3  
kiwisolver                1.4.4            py37h6a678d5_0  
krb5                      1.20.1               h568e23c_1  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.40                 h12ee557_0  
lerc                      3.0                  h295c915_0  
libbrotlicommon           1.0.9                h5eee18b_8  
libbrotlidec              1.0.9                h5eee18b_8  
libbrotlienc              1.0.9                h5eee18b_8  
libclang                  14.0.6          default_hc6dbbc7_1  
libclang13                14.0.6          default_he11475f_1  
libcups                   2.4.2                ha637b67_0  
libcurl                   8.2.1                h91b91d3_0  
libdeflate                1.17                 h5eee18b_1  
libedit                   3.1.20230828         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libevent                  2.1.12               h8f2d780_0  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libglib                   2.78.4               hdc74915_0  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h5eee18b_3  
libllvm14                 14.0.6               hecde1de_4  
libnghttp2                1.52.0               ha637b67_1  
libpng                    1.6.39               h5eee18b_0  
libpq                     12.15                h37d81fd_1  
libssh2                   1.10.0               h37d81fd_2  
libstdcxx-ng              11.2.0               h1234567_1  
libtiff                   4.5.1                h6a678d5_0  
libuuid                   1.41.5               h5eee18b_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
libxcb                    1.15                 h7f8727e_0  
libxkbcommon              1.0.1                h5eee18b_1  
libxml2                   2.10.3               hcbfbd50_0  
libxslt                   1.1.37               h2085143_0  
lz4-c                     1.9.4                h6a678d5_1  
lzo                       2.10                 h7b6447c_2  
matplotlib                3.5.3            py37h06a4308_0  
matplotlib-base           3.5.3            py37hf590b9c_0  
mgkit                     0.4.2            py37h516909a_0    bioconda
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.1            py37hd3c417c_0  
mkl_random                1.2.2            py37h51133e4_0  
mock                      4.0.3              pyhd3eb1b0_0  
msgpack-python            1.0.3            py37hd09550d_0  
munkres                   1.1.4                      py_0  
mysql                     5.7.24               he378463_2  
ncurses                   6.4                  h6a678d5_0  
networkx                  2.6.3              pyhd3eb1b0_0  
nspr                      4.35                 h6a678d5_0  
nss                       3.89.1               h6a678d5_0  
numexpr                   2.8.4            py37he184ba9_0  
numpy                     1.21.5           py37h6c91a56_3  
numpy-base                1.21.5           py37ha15fc14_3  
openssl                   1.1.1w               h7f8727e_0  
packaging                 22.0             py37h06a4308_0  
pandas                    1.3.5            py37h8c16a72_0  
patsy                     0.5.3            py37h06a4308_0  
pcre2                     10.42                hebb0a14_1  
pillow                    9.4.0            py37h6a678d5_0  
pip                       22.3.1           py37h06a4308_0  
pluggy                    1.2.0                    pypi_0    pypi
ply                       3.11                     py37_0  
pycparser                 2.21               pyhd3eb1b0_0  
pymongo                   3.12.0           py37h295c915_0  
pyopenssl                 23.0.0           py37h06a4308_0  
pyparsing                 3.0.9            py37h06a4308_0  
pyqt                      5.15.7           py37h6a678d5_1  
pyqt5-sip                 12.11.0          py37h6a678d5_1  
pysam                     0.15.4           py37hbcae180_0    bioconda
pysocks                   1.7.1                    py37_1  
pytables                  3.7.0            py37hf19a122_1  
pytest                    7.4.4                    pypi_0    pypi
pytest-console-scripts    1.4.0                    pypi_0    pypi
pytest-datadir            1.4.1                    pypi_0    pypi
python                    3.7.16               h7a1cb2a_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
pytz                      2022.7           py37h06a4308_0  
qt-main                   5.15.2               h5b8104b_9  
qt-webengine              5.15.9               h9ab4d14_7  
qtwebkit                  5.212                h3fafdc1_5  
readline                  8.2                  h5eee18b_0  
requests                  2.28.1           py37h06a4308_0  
scipy                     1.7.3            py37h6c91a56_2  
semidbm                   0.5.1              pyh864c0ab_3    bioconda
setuptools                65.6.3           py37h06a4308_0  
sip                       6.6.2            py37h6a678d5_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.45.3               h5eee18b_0  
statsmodels               0.13.5           py37h7deecbd_1  
tk                        8.6.14               h39e8969_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1                    pypi_0    pypi
tornado                   6.2              py37h5eee18b_0  
tqdm                      4.64.1           py37h06a4308_0  
typing_extensions         4.4.0            py37h06a4308_0  
urllib3                   1.26.14          py37h06a4308_0  
wheel                     0.38.4           py37h06a4308_0  
xz                        5.2.10               h5eee18b_1  
zipp                      3.11.0           py37h06a4308_0  
zlib                      1.2.13               h5eee18b_1  
zstd                      1.5.5                hc292b87_0 
```
